# API server image
image:
  repository: kais-api
  tag: "latest"
  pullPolicy: IfNotPresent

# Number of replicas
replicaCount: 1

# API server port
port: 3000

# NATS connection
nats:
  url: "nats://nats.kais-system.svc.cluster.local:4222"

# Postgres connection
postgres:
  url: "postgres://postgres:kais@postgres-postgresql.kais-system.svc.cluster.local:5432/kais"

# Resource limits
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "500m"

# Namespace to deploy into
namespace: kais-system

# Log level
logLevel: info
