apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-kais-operator
  labels:
    app.kubernetes.io/name: kais-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: kais
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-kais-operator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
