apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kais-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kais-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: kais
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kais-api
    app.kubernetes.io/instance: {{ .Release.Name }}
